##
## \file Makefile
## Folder 
## 
## \author Jean-Baptiste Laurent
## \<jeanbaptiste.laurent.pro@gmail.com\>
## 
## \date Started on  Thu Nov 21 02:20:14 2013 Jean-Baptiste Laurent
## \date Last update Thu Nov 21 04:06:24 2013 Jean-Baptiste Laurent
## \brief Description du fichier
##

all:
	javac *.java && java Main

clean:
	rm *.class